version: 2.1

orbs:
  node: circleci/node@5.0.0

jobs:
  build:
    machine:
      image: ubuntu-1604-cuda-10.1:201909-23

    steps:
      - node/install:
          install-yarn: true
          node-version: '16.13'
      - run: node index.js
